-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.detail_transaksi
(
    id serial NOT NULL,
    id_transaksi integer,
    id_obat integer,
    jumlah integer NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    CONSTRAINT detail_transaksi_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.obat
(
    id serial NOT NULL,
    nama character varying(100) COLLATE pg_catalog."default" NOT NULL,
    harga integer NOT NULL,
    stok integer NOT NULL,
    deskripsi text COLLATE pg_catalog."default",
    jenis_obat jenis_obat_enum NOT NULL,
    CONSTRAINT obat_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pelanggan
(
    id serial NOT NULL,
    nama character varying(100) COLLATE pg_catalog."default" NOT NULL,
    alamat character varying(255) COLLATE pg_catalog."default",
    telepon character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT pelanggan_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id serial NOT NULL,
    nama_produk character varying(255) COLLATE pg_catalog."default" NOT NULL,
    harga numeric(10, 2) NOT NULL,
    stok integer NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id serial NOT NULL,
    session_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.suppliers
(
    id serial NOT NULL,
    nama_supplier character varying(255) COLLATE pg_catalog."default" NOT NULL,
    kontak character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transaksi
(
    id serial NOT NULL,
    id_pelanggan integer,
    tanggal timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    total numeric(10, 2) NOT NULL,
    id_pembayaran integer,
    CONSTRAINT transaksi_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.pembayaran
(
    id serial NOT NULL,
    id_transaksi integer NOT NULL,
    metode_pembayaran character varying(50) NOT NULL,
    jumlah_bayar numeric(10, 2),
    id_pembayaran character varying(50),
    CONSTRAINT pembayaran_pkey PRIMARY KEY (id),
    CONSTRAINT pembayaran_id_transaksi_fkey FOREIGN KEY (id_transaksi)
        REFERENCES public.transaksi (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.detail_transaksi
    ADD CONSTRAINT detail_transaksi_id_obat_fkey FOREIGN KEY (id_obat)
    REFERENCES public.obat (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detail_transaksi
    ADD CONSTRAINT detail_transaksi_id_transaksi_fkey FOREIGN KEY (id_transaksi)
    REFERENCES public.transaksi (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.transaksi
    ADD CONSTRAINT transaksi_id_pelanggan_fkey FOREIGN KEY (id_pelanggan)
    REFERENCES public.pelanggan (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE public.transaksi
ADD CONSTRAINT transaksi_id_pembayaran_fkey FOREIGN KEY (id_pembayaran)
    REFERENCES public.pembayaran (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;